set ROOT_DIR=C:\DATA\GitHub\CS\

call VisualStudioRebuild.bat %ROOT_DIR%BackGroundWorker       BackGroundWorker
call VisualStudioRebuild.bat %ROOT_DIR%Bmp2Gif                Bmp2Gif
call VisualStudioRebuild.bat %ROOT_DIR%CaptureWindow          CaptureWindow
call VisualStudioRebuild.bat %ROOT_DIR%Cheetos                Cheetos
call VisualStudioRebuild.bat %ROOT_DIR%ChotChotChat           ChotChotChat
call VisualStudioRebuild.bat %ROOT_DIR%Class_List             Class_List
call VisualStudioRebuild.bat %ROOT_DIR%ContextHelp            ContextHelp
call VisualStudioRebuild.bat %ROOT_DIR%DrawImage              DrawImage
call VisualStudioRebuild.bat %ROOT_DIR%EncodeDecode           EncodeDecode
call VisualStudioRebuild.bat %ROOT_DIR%FFEdit                 FFEdit
call VisualStudioRebuild.bat %ROOT_DIR%FileArranger           FileArranger
call VisualStudioRebuild.bat %ROOT_DIR%FizzBuzz               FizzBuzz
call VisualStudioRebuild.bat %ROOT_DIR%Graphics               Graphics
call VisualStudioRebuild.bat %ROOT_DIR%HelloWolrd             HelloWolrd
call VisualStudioRebuild.bat %ROOT_DIR%ImageViewer            ImageViewer
call VisualStudioRebuild.bat %ROOT_DIR%MultiScreen            MultiScreen
call VisualStudioRebuild.bat %ROOT_DIR%PictMerge              PictMerge
call VisualStudioRebuild.bat %ROOT_DIR%PictMerge              PictMerge2
call VisualStudioRebuild.bat %ROOT_DIR%PictTriming            PictTriming
call VisualStudioRebuild.bat %ROOT_DIR%PlantUML               PlantUML
call VisualStudioRebuild.bat %ROOT_DIR%ProgressBar            ProgressBar
call VisualStudioRebuild.bat %ROOT_DIR%ResizeImg              ResizeImg
call VisualStudioRebuild.bat %ROOT_DIR%StaticAnalysisViewer   StaticAnalysisViewer
call VisualStudioRebuild.bat %ROOT_DIR%SystemGrLauncher       SystemGrLauncher
call VisualStudioRebuild.bat %ROOT_DIR%TabControl             TabControl
call VisualStudioRebuild.bat %ROOT_DIR%Thumnail               Thumnail
call VisualStudioRebuild.bat %ROOT_DIR%VariableArgument       VariableArgument
call VisualStudioRebuild.bat %ROOT_DIR%WeeklyReportFormater   WeeklyReportFormater
call VisualStudioRebuild.bat %ROOT_DIR%WindowJack             WindowJack
call VisualStudioRebuild.bat %ROOT_DIR%XmlReadWrite           XmlReadWrite
call VisualStudioRebuild.bat %ROOT_DIR%othello                othello
