call P4_CommonSetting.bat

set CHANGE_LIST=12345
set BRUNCH_MAP_NAME=TOOL_BRUNCH_MAP_SAMPLE
set BASE_LABEL_NAME=Sample_20190101
set TARGET_TREE=//depot/Source/C#/Sample/...

p4 integrate -c %CHANGE_LIST% -b %BRUNCH_MAP_NAME% -s %TARGET_TREE%@%BASE_LABEL_NAME%
